server:
  port: 0

spring:
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
    rsocket:
      mapping: graphql
  rsocket:
    server:
      port: 8081
